#-------------------------------
# General Site Settings

title: Nicolas Gondard
logo: 
author: Nicolas Gondard
description: Nicolas Gondard's website
email: nicolas.gondard@mines-nancy.org
copyright: Content Copyright &copy; 2021 [Nicolas Gondard](.) Design Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)
address: GitHub B.V., <br>Vijzelstraat 68-72,<br>1017 HL Amsterdam,<br> Pays-Bas
phone: +45 71 44 53 25

menu:
- {name: About, link: '/about'}
- {name: Blog, link: '/blog'}
#- {name: Portfolio, link: '/portfolio'}
- {name: Contact, link: '/contact'}


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: Hi! I’m <br>Nicolas,<br> Product Owner

social:
- {icon: "ti-facebook", link: "#"}
- {icon: "ti-instagram", link: "#"}
- {icon: "ti-dribbble", link: "#"}
- {icon: "ti-twitter", link: "#"}


#-------------------------------
# About (Section and Page)

# About Section
blurb:
  As a Product Owner, I represent the business in IT projects. I have a reasonable command of several economical fields, such as energy, telecom, media. Besides, I used to work abroad (Chile, Yemen, Thailand, Nigeria) between 1993 and 1997.

blurb-btn-link: '/about'
blurb-btn-name: know more


# About Page

# Work Process Section
work-process:
  - title : "Analyse and describe"
    icon : "assets/images/icons/plan.png"
    content : "During this stage, I lead interviews with the business and build the project's grounds."
    
  - title : "Design and Develop"
    icon : "assets/images/icons/design.png"
    content : "While liaising with the development team, for instance in daily meetings, I follow the project up. I take the relevant actions, such as letting the operation team know of the technical requirements."
    
  - title : "Deliver"
    icon : "assets/images/icons/print.png"
    content : "I set up the user acceptance tests. When ready, I liaise with the business and the operations teams to schedule the production release."


#-------------------------------
# Skills Section

skills-title: Skills
skills:
- {name: Project Management, color: '#fdb157', value: '70%'}
- {name: Agile, color: '#9473e6', value: '60%'}
- {name: User Acceptance Test, color: '#bdecf6', value: '60%'}
- {name: Web Development, color: '#ffbcaa', value: '30%'}


#-------------------------------
# Experience Section

experience-title: Experience
experience:
- {name: oil industry, icon: 'icon-1.png', date: '1993 - 1999', organization: 'Total, Schlumberger'}
- {name: energy, icon: 'icon-2.png', date: '2004 - 2011', organization: 'Orano group'}
- {name: media/com, icon: 'icon-3.png', date: '2002 - 2003 and since 2011', organization: 'mainly Argus de la Presse'}


#-------------------------------
# Education Section

education-title: Education
education:
- {name: Ingénieur Civil des Mines, date: '1993', organization: 'Ecole des Mines de Nancy'}
- {name: Master (DEA) in Civil and Mining Engineering, date: '1993', organization: 'Ecole des Mines de Nancy'}
- {name: Classes prépa, date: '1990', organization: 'Lycée Louis le Grand'}
- {name: Baccalauréat C Mention Très Bien, date: '1987', organization: 'Lycée Marceau'}


#-------------------------------
# Services Section

services-title: Misc
services:
- {
    name: Intercultural awareness,
    icon: ti-palette,
    description: 'Each of us has a unique background, either cultural or job-oriented. When I talk or I write to somebody, I take special care of this, thanks to my life abroad!',
    active: # Add true to select section
  }
- {
    name: Community work,
    icon: ti-vector,
    description: 'I volunteered as an health assistant during an holiday camp for disabled persons.',
    active: true # Add true to select section
  }
- {
    name: Oldies,
    icon: ti-panel,
    description: 'I am keen on old car / bike /radio design.',
    active: # Add true to select section
  }


#-------------------------------
# Client Slider Section

client-slider-items:
  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: Nicolas.gondard@mines-nancy.org
